name: aqueduct
version: 0.9.0
description: A fully featured server-side framework built for productivity and testability.
author: stable|kernel
homepage: https://github.com/stablekernel/aqueduct
documentation:

dependencies:
  safe_config: "^1.0.2"
  yaml: any
  matcher: any
  http_server: any
  pbkdf2: any
  crypto: any
  http: any
  logging: any
  analyzer: any
  postgresql: '0.3.3'

dev_dependencies:
  test: any