name: aqueduct
version: 0.0.1
description: A pipeline for building web services
dependencies:
  safe_config: "^1.0.2"
  yaml: any
  matcher: any
  http_server: any
  pbkdf2: any
  crypto: any
  http: any
  logging: any
  analyzer: any
  postgresql: '0.3.2'

dev_dependencies:
  test: any