name: monadart
version: 0.0.1
description: A pipeline for building web services
dependencies:
  http_server: any
  pbkdf2: any
  crypto: any
  http: any

dev_dependencies:
  test: any
  inquirer_pgsql:
    git:
      url: https://github.com/stablekernel/inquirer_pgsql.git
      ref: master
